version: '3'
services:
  sonarqube:
    image: sonarqube:9.9-community
    container_name: sonarqube
    restart: always
    privileged: true
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./sonar.properties:/opt/sonarqube/conf/sonar.properties"
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          cpus: 4
    networks:
      - default

  db:
    image: postgres:12
    container_name: sonarqube-db
    restart: always
    privileged: true
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - "/etc/localtime:/etc/localtime"
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: 2
    networks:
      - default

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:

networks:
  default:
    driver: bridge
    external:
      name: jenkins_default
